### ISSUE TITLE
Encounter error with parameter (--ts) and cannot conver all SVG successfully.

### ISSUE THREAD

**Issue by madeinquant** [khorark/svg2rn#8]
Thank for you contribution. It is a usefully utility and saved a lot of time to convert SVG.  I tried to convert this dataset (http://map-icons.com) and found the following error when I enable the parameter (--ts). Moreover, there are 167 SVG files out of  174 SVG files which can be converted successfully. Please feel free to contact me, if you have any query.

 2 | import Svg, { Path } from "react-native-svg";
  3 | 
> 4 | const Zoom-outIcon = props => <Svg baseProfile="tiny" width={50} height={50} viewBox="0 0 50 50" overflow="inherit" {...props}><Path d="M2 20h46v10H2z" /></Svg>;
    |           ^
  5 | 
  6 | export default Zoom - outIcon;
    at e (/usr/local/lib/node_modules/svg2rn/node_modules/prettier/parser-babylon.js:1:282)
    at Object.parse (/usr/local/lib/node_modules/svg2rn/node_modules/prettier/parser-babylon.js:1:262260)
    at Object.parse (/usr/local/lib/node_modules/svg2rn/node_modules/prettier/index.js:9739:19)
    at coreFormat (/usr/local/lib/node_modules/svg2rn/node_modules/prettier/index.js:13252:23)
    at format (/usr/local/lib/node_modules/svg2rn/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (/usr/local/lib/node_modules/svg2rn/node_modules/prettier/index.js:13526:12)
    at /usr/local/lib/node_modules/svg2rn/node_modules/prettier/index.js:44207:15
    at Object.format (/usr/local/lib/node_modules/svg2rn/node_modules/prettier/index.js:44226:12)
    at prettierPlugin (/usr/local/lib/node_modules/svg2rn/node_modules/@svgr/plugin-prettier/lib/index.js:18:28)
    at run (/usr/local/lib/node_modules

**Comment by madeinquant** [comment]
I found that there are some defect in dataset.

**Comment by khorark** [comment]
Hello! Thank you for your report! 

I viewed dataset and some images have error format (they have only 'undefined' text in svg). See image example. 

![image](https://user-images.githubusercontent.com/16165654/74648069-f9b74e80-518d-11ea-8227-c81ac8f9a668.png)
I added check for this error and now you can see this error in console. 
![image](https://user-images.githubusercontent.com/16165654/74648129-1d7a9480-518e-11ea-80da-7166a9aee743.png)

Please, updated your version. If I can help you anything, tell me please.

Good luck.

**Comment by madeinquant** [comment]
Testing it, get back to you shortly. Thank you.
